# Generated by Django 4.1.7 on 2023-03-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('op_start_time', models.TimeField()),
                ('op_end_time', models.TimeField()),
                ('consultation_charge', models.IntegerField()),
            ],
        ),
    ]
