# Generated by Django 4.1.7 on 2023-03-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='available_count',
            field=models.IntegerField(),
        ),
    ]
