# Generated by Django 4.1.7 on 2023-03-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_department_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
